/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println(javaScriptLinter("./src/main/resources/gates.js"));
    }

    public String getGreeting() {
        return "Hello world.";
    }

    // scanning came from https://docs.oracle.com/javase/tutorial/essential/io/scanning.html
    public static String javaScriptLinter(String fileLocation){
        Scanner s = null;

        String errorMessage = "";
        int lineNumber = 0;

        try {
            s = new Scanner(new BufferedReader(new FileReader(fileLocation)));
            while (s.hasNextLine()){
                lineNumber ++;
                String line = s.nextLine();
                Character lastChar = ' ';

                // check for empty line, change last character if not empty
                if ( line.length() > 0 ){
                    lastChar = line.charAt(line.length()-1);
                }

                if (lastChar.equals(' ') ||
                        lastChar.equals(';') ||
                        lastChar.equals('{') ||
                        lastChar.equals('}') ||
                        line.contains("if") ||
                        line.contains("else")
                ){
                    // no error, end of line is valid
                } else {
                   errorMessage += String.format("Line %d: Missing semicolon.%n", lineNumber);
                }
            }

        } catch (FileNotFoundException e) {
            System.out.println("This file was not found");
        }

        return errorMessage;
    }

}
